export const SHOW_AUTH_LOADING = 'AUTH/SHOW_AUTH_LOADING';
export const LOAD_AUTH_ERROR = 'AUTH/LOAD_AUTH_ERROR';
export const LOAD_AUTH_SUCCESS = 'AUTH/LOAD_AUTH_SUCCESS';
export const HIDE_AUTH_LOADING = 'AUTH/HIDE_AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH/AUTH_LOGOUT';
