export const SHOW_CREATEUSER_LOADING = 'CREATEUSER/SHOW_CREATEUSER_LOADING';
export const LOAD_CREATEUSER_ERROR = 'CREATEUSER/LOAD_CREATEUSER_ERROR';
export const LOAD_CREATEUSER_SUCCESS = 'CREATEUSER/LOAD_CREATEUSER_SUCCESS';
export const HIDE_CREATEUSER_LOADING = 'CREATEUSER/HIDE_CREATEUSER_LOADING';
