export const SHOW_USERLIST_LOADING = 'USERLIST/SHOW_USERLIST_LOADING';
export const LOAD_USERLIST_ERROR = 'USERLIST/LOAD_USERLIST_ERROR';
export const LOAD_USERLIST_SUCCESS = 'USERLIST/LOAD_USERLIST_SUCCESS';
export const HIDE_USERLIST_LOADING = 'USERLIST/HIDE_USERLIST_LOADING';
