export const SHOW_COMMENTLIST_LOADING = 'COMMENTLIST/SHOW_COMMENTLIST_LOADING';
export const LOAD_COMMENTLIST_ERROR = 'COMMENTLIST/LOAD_COMMENTLIST_ERROR';
export const LOAD_COMMENTLIST_SUCCESS = 'COMMENTLIST/LOAD_COMMENTLIST_SUCCESS';
export const HIDE_COMMENTLIST_LOADING = 'COMMENTLIST/HIDE_COMMENTLIST_LOADING';
