export const SHOW_EDITUSER_LOADING = 'EDITUSER/SHOW_EDITUSER_LOADING';
export const LOAD_EDITUSER_ERROR = 'EDITUSER/LOAD_EDITUSER_ERROR';
export const LOAD_EDITUSER_SUCCESS = 'EDITUSER/LOAD_EDITUSER_SUCCESS';
export const HIDE_EDITUSER_LOADING = 'EDITUSER/HIDE_EDITUSER_LOADING';
export const CLEAR_EDITUSER_LOADING = 'EDITUSER/CLEAR_EDITUSER_LOADING';
