export const SHOW_POSTLIST_LOADING = 'POSTLIST/SHOW_POSTLIST_LOADING';
export const LOAD_POSTLIST_ERROR = 'POSTLIST/LOAD_POSTLIST_ERROR';
export const LOAD_POSTLIST_SUCCESS = 'POSTLIST/LOAD_POSTLIST_SUCCESS';
export const HIDE_POSTLIST_LOADING = 'POSTLIST/HIDE_POSTLIST_LOADING';
export const SHOW_POSTLIST_POSTINFO = 'POSTLIST/SHOW_POSTLIST_POSTINFO';
export const HIDE_POSTLIST_POSTINFO = 'POSTLIST/HIDE_POSTLIST_POSTINFO';
