export const SHOW_USERPROFILE_LOADING = 'USERPROFILE/SHOW_USERPROFILE_LOADING';
export const LOAD_USERPROFILE_ERROR = 'USERPROFILE/LOAD_USERPROFILE_ERROR';
export const LOAD_USERPROFILE_SUCCESS = 'USERPROFILE/LOAD_USERPROFILE_SUCCESS';
export const HIDE_USERPROFILE_LOADING = 'USERPROFILE/HIDE_USERPROFILE_LOADING';
